-- Generated by `npm run sync-content` — do not hand-edit.
-- Apply with: wrangler d1 execute twolosttourists-blog --local/--remote --file=d1/seed.sql

DELETE FROM posts WHERE slug NOT IN ('replacing-house-batteries');

INSERT INTO posts (slug, title, excerpt, tags_flat, published_at, draft) VALUES ('replacing-house-batteries', 'Replacing the House Battery Bank', 'Pull a failed AGM house bank, size the replacement, and torque the terminals back to spec.', 'restoration electrical batteries', '2026-05-18', 0)
  ON CONFLICT(slug) DO UPDATE SET title=excluded.title, excerpt=excluded.excerpt, tags_flat=excluded.tags_flat, published_at=excluded.published_at, draft=excluded.draft, synced_at=CURRENT_TIMESTAMP;
