import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const POSTS_DIR = path.join(process.cwd(), "content", "posts");
const OUTPUT_FILE = path.join(process.cwd(), "d1", "seed.sql");

function escapeSql(value) {
	return String(value).replace(/'/g, "''");
}

const filenames = fs.readdirSync(POSTS_DIR).filter((f) => f.endsWith(".mdx"));

const posts = filenames.map((filename) => {
	const slug = filename.replace(/\.mdx$/, "");
	const raw = fs.readFileSync(path.join(POSTS_DIR, filename), "utf8");
	const { data } = matter(raw);
	return {
		slug,
		title: data.title ?? "",
		excerpt: data.excerpt ?? "",
		tags: Array.isArray(data.tags) ? data.tags : [],
		date: data.date ?? "",
		draft: Boolean(data.draft),
	};
});

const published = posts.filter((p) => !p.draft);

const lines = [];
lines.push("-- Generated by `npm run sync-content` — do not hand-edit.");
lines.push(
	"-- Apply with: wrangler d1 execute twolosttourists-blog --local/--remote --file=d1/seed.sql",
);
lines.push("");

if (published.length > 0) {
	const slugList = published.map((p) => `'${escapeSql(p.slug)}'`).join(", ");
	lines.push(`DELETE FROM posts WHERE slug NOT IN (${slugList});`);
} else {
	lines.push("DELETE FROM posts;");
}
lines.push("");

for (const post of published) {
	const tagsFlat = post.tags.join(" ");
	lines.push(
		`INSERT INTO posts (slug, title, excerpt, tags_flat, published_at, draft) VALUES ('${escapeSql(post.slug)}', '${escapeSql(post.title)}', '${escapeSql(post.excerpt)}', '${escapeSql(tagsFlat)}', '${escapeSql(post.date)}', 0)\n` +
			`  ON CONFLICT(slug) DO UPDATE SET title=excluded.title, excerpt=excluded.excerpt, tags_flat=excluded.tags_flat, published_at=excluded.published_at, draft=excluded.draft, synced_at=CURRENT_TIMESTAMP;`,
	);
}

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, lines.join("\n") + "\n");
console.log(`Wrote ${OUTPUT_FILE} (${published.length} post(s)).`);
